//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileUpload_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResimYukle
    {
        public int resimId { get; set; }
        public string resimAdi { get; set; }
        public string resimUzanti { get; set; }
        public string resimTuru { get; set; }
        public string resimBoyutu { get; set; }
        public string resimAciklama { get; set; }

        
    }
}
